# EXPERIMENT–2: Text Retrieval and Text Processing

**Tasks:**
1. Obtain a Twitter/X tweet dataset from Kaggle and load it into Colab.
2. Extract the first 100 tweets and save them to a file.
3. Perform sentence tokenization.
4. Perform word tokenization.
5. Perform basic tweet cleaning and word-frequency analysis.

> **Note:** This notebook is designed to work with the Kaggle dataset downloaded in the previous step. Upload the CSV file when prompted. The notebook automatically detects common tweet/text column names.

## 1. Install and import required libraries

In [34]:
for i in range(1,10+1):
  print(i)

1
2
3
4
5
6
7
8
9
10

In [ ]:
!pip install -q nltk pandas

import os
import re
import glob
import pandas as pd
from collections import Counter
from google.colab import files
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

## 2. Upload the Kaggle tweet dataset

In [ ]:
uploaded = files.upload()
print('Uploaded files:', list(uploaded.keys()))

Saving Tweets.csv to Tweets.csv
Uploaded files: ['Tweets.csv']

## 3. Locate and read the CSV file

In [ ]:
x = 10/0
print(x)
print('Hello World')

IndentationError: expected an indented block after 'try' statement on line 1 (564287051.py, line 2)

In [ ]:
csv_files = glob.glob('*.csv')
if not csv_files:
    raise FileNotFoundError('No CSV file found. Please upload the Kaggle CSV dataset.')

print('CSV files found:')
for f in csv_files:
    print(' -', f)

csv_file = csv_files[0]
df = pd.read_csv(csv_file)

print('\nUsing:', csv_file)
print('Dataset shape:', df.shape)
print('\nColumns:')
print(df.columns.tolist())

display(df.head())

CSV files found:
 - Tweets.csv

Using: Tweets.csv
Dataset shape: (27481, 4)

Columns:
['textID', 'text', 'selected_text', 'sentiment']

,textID,text,selected_text,sentiment
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative
2,088c60f138,my boss is bullying me...,bullying me,negative
3,9642c003ef,what interview! leave me alone,leave me alone,negative
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative

## 4. Identify the tweet/text column

In [ ]:
common_text_columns = [
    'text', 'tweet', 'tweets', 'content', 'full_text',
    'Tweet', 'Tweets', 'Text', 'Content', 'fullText'
]

text_column = None
for col in common_text_columns:
    if col in df.columns:
        text_column = col
        break

if text_column is None:
    # Fallback: choose the object/string column with the largest average length.
    object_cols = df.select_dtypes(include=['object', 'string']).columns.tolist()
    if not object_cols:
        raise ValueError('No text/string column was found. Please inspect the dataset columns.')
    avg_lengths = {c: df[c].dropna().astype(str).str.len().mean() for c in object_cols}
    text_column = max(avg_lengths, key=avg_lengths.get)

print('Selected text column:', text_column)
print('\nSample text:')
print(df[text_column].dropna().iloc[0])

Selected text column: text

Sample text:
 I`d have responded, if I were going

## 5. Extract the first 100 tweets

In [ ]:
tweets = df[text_column].dropna().astype(str).head(100).reset_index(drop=True)

print('Number of tweets extracted:', len(tweets))

display(pd.DataFrame({'Tweet No.': range(1, len(tweets)+1), 'Tweet': tweets}))

Number of tweets extracted: 100

    Tweet No.                                              Tweet
0           1                I`d have responded, if I were going
1           2      Sooo SAD I will miss you here in San Diego!!!
2           3                          my boss is bullying me...
3           4                     what interview! leave me alone
4           5   Sons of ****, why couldn`t they put them on t...
..        ...                                                ...
95         96        Happy Mothers day to all you Mums out there
96         97   CASEY`S GONE?!?! BUT WHY?! So, she piddled a ...
97         98       hemp cloth is marvelous but unfortunately no
98         99  Gonna read a story bout adam lambert online th...
99        100     We saw that in none 3D - the baddie`s the best

[100 rows x 2 columns]

## 6. Save the first 100 tweets to a CSV file

In [ ]:
first_100 = pd.DataFrame({
    'tweet_id': range(1, len(tweets) + 1),
    'text': tweets
})

first_100.to_csv('first_100_tweets.csv', index=False)
print('Saved as first_100_tweets.csv')

files.download('first_100_tweets.csv')

Saved as first_100_tweets.csv

## 7. Sentence Tokenization

In [ ]:
sample_text = 'Natural Language Processing is a field of Artificial Intelligence. It helps computers understand human language.'
sentences = sent_tokenize(sample_text)

print('Sample text:\n', sample_text)
print('\nSentence tokens:')
for i, sentence in enumerate(sentences, 1):
    print(f'{i}. {sentence}')

Sample text:
 Natural Language Processing is a field of Artificial Intelligence. It helps computers understand human language.

Sentence tokens:
1. Natural Language Processing is a field of Artificial Intelligence.
2. It helps computers understand human language.

## 8. Word Tokenization

In [ ]:
words = word_tokenize(sample_text)

print('Word tokens:')
print(words)
print('\nNumber of tokens:', len(words))

Word tokens:
['Natural', 'Language', 'Processing', 'is', 'a', 'field', 'of', 'Artificial', 'Intelligence', '.', 'It', 'helps', 'computers', 'understand', 'human', 'language', '.']

Number of tokens: 17

## 9. Sentence Tokenization of the first 100 tweets

In [ ]:
tweet_sentences = []

for tweet_no, tweet in enumerate(tweets, 1):
    for sentence in sent_tokenize(tweet):
        tweet_sentences.append((tweet_no, sentence))

sentence_df = pd.DataFrame(tweet_sentences, columns=['tweet_id', 'sentence'])

print('Total sentences:', len(sentence_df))
display(sentence_df.head(20))

Total sentences: 152

    tweet_id                                           sentence
0          1                I`d have responded, if I were going
1          2       Sooo SAD I will miss you here in San Diego!!
2          2                                                  !
3          3                          my boss is bullying me...
4          4                                    what interview!
5          4                                     leave me alone
6          5   Sons of ****, why couldn`t they put them on t...
7          6  http://www.dothebouncy.com/smf - some shameles...
8          7  2am feedings for the baby are fun when he is a...
9          8                                         Soooo high
10         9                                        Both of you
11        10                                          Journey!?
12        10                       Wow... u just became cooler.
13        10                       hehe... (is that possible!?)
14        11   as much as i love to be hopeful, i reckon the...
15        12  I really really like the song Love Story by Ta...
16        13       My Sharpie is running DANGERously low on ink
17        14  i want to go to music tonight but i lost my vo...
18        15                         test test from the LG enV2
19        16                              Uh oh, I am sunburned

## 10. Word Tokenization of the first 100 tweets

In [ ]:
tweet_words = []

for tweet_no, tweet in enumerate(tweets, 1):
    tokens = word_tokenize(tweet)
    for token in tokens:
        tweet_words.append((tweet_no, token))

word_df = pd.DataFrame(tweet_words, columns=['tweet_id', 'token'])

print('Total word tokens:', len(word_df))
display(word_df.head(100))

Total word tokens: 1522

    tweet_id      token
0          1          I
1          1          `
2          1          d
3          1       have
4          1  responded
..       ...        ...
95        10     became
96        10     cooler
97        10          .
98        10       hehe
99        10        ...

[100 rows x 2 columns]

## 11. Basic Tweet Cleaning

In [ ]:
def clean_tweet(text):
    text = re.sub(r'https?://\\S+|www\\.\\S+', '', text)  # URLs
    text = re.sub(r'@\\w+', '', text)                       # mentions
    text = re.sub(r'#', '', text)                            # hashtag symbol
    text = re.sub(r'\\s+', ' ', text).strip()               # extra spaces
    return text

processed_df = first_100.copy()
processed_df['cleaned_text'] = processed_df['text'].apply(clean_tweet)

display(processed_df.head(10))

,tweet_id,text,cleaned_text
0,1,"I`d have responded, if I were going","I`d have responded, if I were going"
1,2,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD I will miss you here in San Diego!!!
2,3,my boss is bullying me...,my boss is bullying me...
3,4,what interview! leave me alone,what interview! leave me alone
4,5,"Sons of ****, why couldn`t they put them on t...","Sons of ****, why couldn`t they put them on th..."
5,6,http://www.dothebouncy.com/smf - some shameles...,http://www.dothebouncy.com/smf - some shameles...
6,7,2am feedings for the baby are fun when he is a...,2am feedings for the baby are fun when he is a...
7,8,Soooo high,Soooo high
8,9,Both of you,Both of you
9,10,Journey!? Wow... u just became cooler. hehe....,Journey!? Wow... u just became cooler. hehe.....

## 12. Word Frequency Analysis

In [ ]:
all_words = []

for tweet in processed_df['cleaned_text']:
    tokens = word_tokenize(tweet.lower())
    all_words.extend(tokens)

# Keep only alphanumeric tokens
words_without_punctuation = [word for word in all_words if word.isalnum()]

frequency = Counter(words_without_punctuation)

print('Top 20 words/tokens:')
for word, count in frequency.most_common(20):
    print(f'{word}: {count}')

Top 20 words/tokens:
i: 61
the: 29
and: 29
to: 28
a: 23
you: 21
my: 19
is: 18
in: 16
for: 16
it: 16
of: 13
m: 12
s: 11
so: 11
on: 10
me: 9
na: 9
have: 8
love: 8

## 13. Save the processed data

In [ ]:
processed_df.to_csv('processed_tweets.csv', index=False)
sentence_df.to_csv('sentence_tokens.csv', index=False)
word_df.to_csv('word_tokens.csv', index=False)

print('Files created:')
print('1. first_100_tweets.csv')
print('2. processed_tweets.csv')
print('3. sentence_tokens.csv')
print('4. word_tokens.csv')

Files created:
1. first_100_tweets.csv
2. processed_tweets.csv
3. sentence_tokens.csv
4. word_tokens.csv

## 14. Download the output files

In [ ]:
from google.colab import files

for output_file in [
    'first_100_tweets.csv',
    'processed_tweets.csv',
    'sentence_tokens.csv',
    'word_tokens.csv'
]:
    files.download(output_file)

## Result

The first 100 tweets from the Kaggle dataset were extracted and stored in a CSV file. The tweets were successfully processed using sentence tokenization and word tokenization. Basic cleaning and word-frequency analysis were also performed.

## Viva Questions
1. What is text retrieval?
2. What is tokenization?
3. What is sentence tokenization?
4. What is word tokenization?
5. What is the difference between a word and a token?
6. Why is text preprocessing required?
7. What is NLTK?
8. Why are URLs and mentions removed from tweets?
9. What is the purpose of `word_tokenize()`?
10. What is the purpose of `sent_tokenize()`?
11. Why is punctuation removed during frequency analysis?
12. What is the purpose of `Counter()`?